export const cities: Record<string, string[]> = {
  'Adana': ['Seyhan', 'Yuregir', 'Cukurova', 'Saricam', 'Karaisali', 'Pozanti', 'Aladag', 'Feke', 'Saimbeyli', 'Tufanbeyli', 'Kozan', 'Ceyhan', 'Imamoglu', 'Karatas', 'Yumurtalik'],
  'Adiyaman': ['Merkez', 'Besni', 'Kahta', 'Golbasi', 'Gerger', 'Celikhan', 'Samsat', 'Sincik', 'Tut'],
  'Afyonkarahisar': ['Merkez', 'Sandikli', 'Bolvadin', 'Emirdag', 'Dinar', 'Sultandagi', 'Sinanpasa', 'Iscehisar', 'Suhut', 'Basmakcı', 'Bayat', 'Cobanlar', 'Dazkiri', 'Evciler', 'Hocalar', 'Ihsaniye', 'Kiziloren'],
  'Agri': ['Merkez', 'Dogubayazit', 'Patnos', 'Diyadin', 'Eleşkirt', 'Hamur', 'Taslicay', 'Tutak'],
  'Aksaray': ['Merkez', 'Ortakoy', 'Eskil', 'Guzelyurt', 'Agacoren', 'Gulagac', 'Sariyahsi', 'Sultanhanı'],
  'Amasya': ['Merkez', 'Merzifon', 'Suluova', 'Tasova', 'Goynucek', 'Gumushacikoy', 'Hamamozu'],
  'Ankara': ['Cankaya', 'Kecioren', 'Mamak', 'Etimesgut', 'Sincan', 'Yenimahalle', 'Altindag', 'Pursaklar', 'Polatli', 'Golbasi', 'Cubuk', 'Beypazari', 'Haymana', 'Sereflikochisar', 'Akyurt', 'Bala', 'Elmadag', 'Evren', 'Gudul', 'Kalecik', 'Kazan', 'Kizilcahamam', 'Nallihan'],
  'Antalya': ['Muratpasa', 'Kepez', 'Konyaalti', 'Aksu', 'Dosemealti', 'Alanya', 'Manavgat', 'Serik', 'Kemer', 'Kumluca', 'Kas', 'Finike', 'Demre', 'Elmali', 'Korkuteli', 'Akseki', 'Gazipasa', 'Gundogmus', 'Ibradi'],
  'Ardahan': ['Merkez', 'Gole', 'Cildir', 'Hanak', 'Posof', 'Damal'],
  'Artvin': ['Merkez', 'Hopa', 'Borcka', 'Arhavi', 'Savsat', 'Ardanuc', 'Yusufeli', 'Murgul'],
  'Aydin': ['Efeler', 'Kusadasi', 'Didim', 'Nazilli', 'Soke', 'Cine', 'Germencik', 'Incirliova', 'Bozdogan', 'Sultanhisar', 'Buharkent', 'Karacasu', 'Kuyucak', 'Kocarli', 'Kosk', 'Yenipazar'],
  'Balikesir': ['Altieylul', 'Karesi', 'Bandirma', 'Edremit', 'Gonen', 'Burhaniye', 'Ayvalik', 'Erdek', 'Susurluk', 'Bigadic', 'Dursunbey', 'Havran', 'Ivrindi', 'Kepsut', 'Manyas', 'Marmara', 'Savastepe', 'Sindirgi', 'Balikesir Merkez'],
  'Bartin': ['Merkez', 'Ulus', 'Amasra', 'Kurucasile'],
  'Batman': ['Merkez', 'Kozluk', 'Sason', 'Besiri', 'Gercus', 'Hasankeyf'],
  'Bayburt': ['Merkez', 'Aydintepe', 'Demirozu'],
  'Bilecik': ['Merkez', 'Bozuyuk', 'Sogut', 'Osmaneli', 'Pazaryeri', 'Golpazari', 'Inhisar', 'Yenipazar'],
  'Bingol': ['Merkez', 'Genc', 'Solhan', 'Karliova', 'Adakli', 'Kigi', 'Yayladere', 'Yedisu'],
  'Bitlis': ['Merkez', 'Tatvan', 'Ahlat', 'Adilcevaz', 'Guroymak', 'Hizan', 'Mutki'],
  'Bolu': ['Merkez', 'Gerede', 'Mudurnu', 'Goynuk', 'Mengen', 'Dortdivan', 'Kibriscik', 'Seben', 'Yeniçaga'],
  'Burdur': ['Merkez', 'Bucak', 'Golhisar', 'Yesilova', 'Tefenni', 'Aglasun', 'Altinyayla', 'Cavdir', 'Celtikci', 'Karamanli', 'Kemer'],
  'Bursa': ['Osmangazi', 'Nilufer', 'Yildirim', 'Gorukle', 'Inegol', 'Gemlik', 'Mudanya', 'Mustafakemalpasa', 'Karacabey', 'Orhangazi', 'Kestel', 'Gursu', 'Iznik', 'Yenisehir', 'Buyukorhan', 'Harmancik', 'Keles', 'Orhaneli'],
  'Canakkale': ['Merkez', 'Biga', 'Can', 'Gelibolu', 'Ayvacik', 'Ezine', 'Yenice', 'Bayramiç', 'Bozcaada', 'Gokceada', 'Lapseki'],
  'Cankiri': ['Merkez', 'Cerkes', 'Ilgaz', 'Kurskale', 'Orta', 'Sabanozu', 'Atkaracalar', 'Bayramoren', 'Eldivan', 'Korgun', 'Yaprakli'],
  'Corum': ['Merkez', 'Osmancik', 'Sungurlu', 'Alaca', 'Iskilip', 'Bayat', 'Kargi', 'Lacin', 'Mecitozu', 'Oguzlar', 'Ortakoy', 'Ugurludag', 'Bogazkale', 'Dodurga'],
  'Denizli': ['Merkezefendi', 'Pamukkale', 'Civril', 'Acipayam', 'Tavas', 'Saraykoy', 'Buldan', 'Cal', 'Cardak', 'Guney', 'Honaz', 'Kale', 'Serinhisar'],
  'Diyarbakir': ['Baglar', 'Kayapinar', 'Yenisehir', 'Sur', 'Bismil', 'Ergani', 'Silvan', 'Cermik', 'Dicle', 'Kulp', 'Lice', 'Hani', 'Hazro', 'Kocakoy', 'Cinar', 'Cungus', 'Egil'],
  'Duzce': ['Merkez', 'Akcakoca', 'Golyaka', 'Gumusova', 'Cumayeri', 'Cilimli', 'Kaynasli', 'Yigilca'],
  'Edirne': ['Merkez', 'Kesan', 'Uzunkopru', 'Havsa', 'Ipsala', 'Enez', 'Lalalpasa', 'Meric', 'Suloglu'],
  'Elazig': ['Merkez', 'Karakocan', 'Kovancilar', 'Palu', 'Maden', 'Baskil', 'Sivrice', 'Aricak', 'Agin', 'Alacakaya', 'Keban'],
  'Erzincan': ['Merkez', 'Tercan', 'Uzumlu', 'Cayirli', 'Refahiye', 'Ilic', 'Kemah', 'Kemaliye', 'Otlukbeli'],
  'Erzurum': ['Yakutiye', 'Palandoken', 'Aziziye', 'Horasan', 'Oltu', 'Pasinler', 'Askale', 'Ispir', 'Tortum', 'Hinis', 'Karayazi', 'Narman', 'Senkaya', 'Tekman', 'Cat', 'Karacoban', 'Koprukoy', 'Olur', 'Pazaryolu', 'Uzundere'],
  'Eskisehir': ['Odunpazari', 'Tepebasi', 'Sivrihisar', 'Cifteler', 'Mahmudiye', 'Alpu', 'Beylikova', 'Gunyuzu', 'Han', 'Inonu', 'Mihalgazi', 'Mihaliccik', 'Saricakaya', 'Seyitgazi'],
  'Gaziantep': ['Sahinbey', 'Sehitkamil', 'Nizip', 'Islahiye', 'Nurdagi', 'Oguzeli', 'Araban', 'Yavuzeli', 'Karkamis'],
  'Giresun': ['Merkez', 'Bulancak', 'Gorele', 'Espiye', 'Tirebolu', 'Eynesil', 'Kesap', 'Piraziz', 'Dereli', 'Dogankent', 'Yaglidere', 'Alucra', 'Sebinkarahisar', 'Camoluk', 'Canakci', 'Guce'],
  'Gumushane': ['Merkez', 'Kelkit', 'Siran', 'Torul', 'Kose', 'Kurtun'],
  'Hakkari': ['Merkez', 'Yuksekova', 'Semdinli', 'Cukurca', 'Derecik'],
  'Hatay': ['Antakya', 'Iskenderun', 'Defne', 'Dortyol', 'Samandag', 'Kirikhan', 'Reyhanli', 'Erzin', 'Altinozu', 'Belen', 'Hassa', 'Kumlu', 'Yayladagi', 'Payas'],
  'Igdir': ['Merkez', 'Tuzluca', 'Aralik', 'Karakoyunlu'],
  'Isparta': ['Merkez', 'Egirdir', 'Yalvac', 'Senirkent', 'Gelendost', 'Keciborlu', 'Sarkikaraagac', 'Sutculer', 'Aksu', 'Atabey', 'Gonen', 'Uluborlu', 'Yenisarbademli'],
  'Istanbul': ['Kadikoy', 'Besiktas', 'Uskudar', 'Sisli', 'Bakirkoy', 'Beyoglu', 'Fatih', 'Sariyer', 'Maltepe', 'Kartal', 'Pendik', 'Atasehir', 'Umraniye', 'Sultanbeyli', 'Tuzla', 'Beykoz', 'Cekmekoy', 'Sancaktepe', 'Sultanahmet', 'Avcilar', 'Bagcilar', 'Bahcelievler', 'Basaksehir', 'Bayrampasa', 'Beylikduzu', 'Buyukcekmece', 'Catalca', 'Esenler', 'Esenyurt', 'Eyupsultan', 'Gaziosmanpasa', 'Gungoren', 'Kagithane', 'Kucukcekmece', 'Silivri', 'Sultangazi', 'Zeytinburnu', 'Arnavutkoy', 'Adalar'],
  'Izmir': ['Konak', 'Bornova', 'Karsiyaka', 'Bayrakli', 'Buca', 'Cigli', 'Gaziemir', 'Narlidere', 'Balcova', 'Guzelbahce', 'Karabaglar', 'Torbali', 'Odemis', 'Bergama', 'Menemen', 'Aliaga', 'Cesme', 'Tire', 'Urla', 'Kemalpasa', 'Seferihisar', 'Selcuk', 'Dikili', 'Foca', 'Kinik', 'Kiraz', 'Bayindir', 'Beydag', 'Karaburun', 'Menderes'],
  'Kahramanmaras': ['Dulkadiroglu', 'Onikisubat', 'Elbistan', 'Afsin', 'Goksun', 'Turkoglu', 'Pazarcik', 'Andirin', 'Caglayancerit', 'Ekinozu', 'Nurhak'],
  'Karabuk': ['Merkez', 'Safranbolu', 'Eskipazar', 'Yenice', 'Eflani', 'Ovacik'],
  'Karaman': ['Merkez', 'Ermenek', 'Ayranci', 'Basyayla', 'Kazimkarabekir', 'Sariveliler'],
  'Kars': ['Merkez', 'Sarikamis', 'Kagizman', 'Digor', 'Selim', 'Arpaçay', 'Susuz', 'Akyaka'],
  'Kastamonu': ['Merkez', 'Tosya', 'Taskopru', 'Inebolu', 'Cide', 'Arac', 'Daday', 'Devrekani', 'Ihsangazi', 'Abana', 'Agii', 'Azdavay', 'Bozkurt', 'Catalzeytin', 'Doganyurt', 'Hanonu', 'Kuere', 'Pinarbaşi', 'Seydiler', 'Senpazar'],
  'Kayseri': ['Melikgazi', 'Kocasinan', 'Talas', 'Hacilar', 'Incesu', 'Develi', 'Bunyan', 'Yahyali', 'Tomarza', 'Pinarbaşi', 'Akkisla', 'Felahiye', 'Ozvatan', 'Sariz', 'Sarkisla', 'Yesilhisar'],
  'Kirikkale': ['Merkez', 'Keskin', 'Delice', 'Yahsihan', 'Baliseyh', 'Bahsili', 'Celebi', 'Karakecili', 'Sulakyurt'],
  'Kirklareli': ['Merkez', 'Luleburgaz', 'Babaeski', 'Vize', 'Pinarhisar', 'Demirkoy', 'Kofalca', 'Pehlivankoy'],
  'Kirsehir': ['Merkez', 'Kaman', 'Mucur', 'Cicekdagi', 'Akpinar', 'Akçakent', 'Boztepe'],
  'Kilis': ['Merkez', 'Musabeyli', 'Elbeyli', 'Polateli'],
  'Kocaeli': ['Izmit', 'Gebze', 'Darica', 'Korfez', 'Derince', 'Golcuk', 'Cayirova', 'Dilovasi', 'Basiskele', 'Kartepe', 'Kandira', 'Karamursel'],
  'Konya': ['Selcuklu', 'Meram', 'Karatay', 'Eregli', 'Aksehir', 'Beyşehir', 'Cihanbeyli', 'Cumra', 'Karapinar', 'Seydisehir', 'Ilgin', 'Kulu', 'Sarayonu', 'Bozkir', 'Huyuk', 'Kadinhani', 'Akoren', 'Altinekin', 'Derebucak', 'Derbent', 'Doganhisar', 'Emirgazi', 'Guneysinir', 'Hadim', 'Halkapinar', 'Taskent', 'Tuzlukcu', 'Yalihuyuk', 'Yunak'],
  'Kutahya': ['Merkez', 'Tavsanli', 'Simav', 'Gediz', 'Emet', 'Domanic', 'Altintas', 'Aslanapa', 'Cavdarhisar', 'Dumlupinar', 'Hisarcik', 'Pazarlar', 'Saphane'],
  'Malatya': ['Battalgazi', 'Yesilyurt', 'Dogansehir', 'Akcadag', 'Darende', 'Hekimhan', 'Arapgir', 'Arguvan', 'Doganyol', 'Kale', 'Kuluncak', 'Puturge', 'Yazihan'],
  'Manisa': ['Yunusemre', 'Sehzadeler', 'Akhisar', 'Turgutlu', 'Salihli', 'Soma', 'Alaşehir', 'Saruhanli', 'Demirci', 'Kirkagac', 'Gordes', 'Kula', 'Ahmetli', 'Golmarmara', 'Koprubasi', 'Sarigol', 'Selendi'],
  'Mardin': ['Artuklu', 'Kiziltepe', 'Midyat', 'Nusaybin', 'Dargecit', 'Derik', 'Mazidagi', 'Omerli', 'Savur', 'Yesilli'],
  'Mersin': ['Akdeniz', 'Mezitli', 'Toroslar', 'Yenisehir', 'Tarsus', 'Silifke', 'Erdemli', 'Anamur', 'Mut', 'Aydincik', 'Bozyazi', 'Camliyayla', 'Gulnar'],
  'Mugla': ['Mentese', 'Bodrum', 'Fethiye', 'Marmaris', 'Milas', 'Dalaman', 'Ortaca', 'Datca', 'Koycegiz', 'Seydikemer', 'Ula', 'Yatagan', 'Kavaklidere'],
  'Mus': ['Merkez', 'Bulanik', 'Malazgirt', 'Varto', 'Hasköy', 'Korkut'],
  'Nevsehir': ['Merkez', 'Urgup', 'Avanos', 'Gulsehir', 'Haci Bektas', 'Kozakli', 'Derinkuyu', 'Acigol'],
  'Nigde': ['Merkez', 'Bor', 'Camardi', 'Ulukisla', 'Altunhisar', 'Ciftlik'],
  'Ordu': ['Altinordu', 'Unye', 'Fatsa', 'Persembe', 'Korgan', 'Kumru', 'Ulubey', 'Golkoy', 'Akkus', 'Aybasti', 'Camas', 'Catalpinar', 'Gulyali', 'Gurgentepe', 'Ikizce', 'Kabaduz', 'Kabatas', 'Mesudiye'],
  'Osmaniye': ['Merkez', 'Kadirli', 'Duzici', 'Bahce', 'Toprakkale', 'Hasanbeyli', 'Sumbas'],
  'Rize': ['Merkez', 'Cayeli', 'Ardesen', 'Pazar', 'Findikli', 'Ardeşen', 'Ikizdere', 'Kalkandere', 'Derepazari', 'Guneysu', 'Hemsin'],
  'Sakarya': ['Adapazari', 'Serdivan', 'Erenler', 'Arifiye', 'Hendek', 'Akyazi', 'Geyve', 'Sapanca', 'Pamukova', 'Kaynarca', 'Sogutlu', 'Karasu', 'Ferizli', 'Karapurcek', 'Kocaali', 'Tarakli'],
  'Samsun': ['Ilkadim', 'Atakum', 'Canik', 'Tekkeköy', 'Bafra', 'Carsamba', 'Terme', 'Vezirkopru', 'Havza', 'Kavak', 'Ladik', 'Salipazari', 'Ayvacik', 'Asarcik', 'Ondokuzmayis', 'Alaçam', 'Yakakent'],
  'Sanliurfa': ['Haliliye', 'Eyyubiye', 'Karakopru', 'Siverek', 'Viransehir', 'Suruc', 'Akcakale', 'Birecik', 'Bozova', 'Ceylanpinar', 'Halfeti', 'Harran', 'Hilvan'],
  'Siirt': ['Merkez', 'Kurtalan', 'Pervari', 'Eruh', 'Baykan', 'Sirvan', 'Tillo'],
  'Sinop': ['Merkez', 'Boyabat', 'Gerze', 'Ayancik', 'Duragan', 'Turkeli', 'Erfelek', 'Dikmen', 'Sarayduzü'],
  'Sivas': ['Merkez', 'Susehri', 'Zara', 'Sarki sla', 'Yildizeli', 'Gemerek', 'Kangal', 'Divrigi', 'Hafik', 'Gurun', 'Imranli', 'Koyulhisar', 'Altinyayla', 'Akincilar', 'Dogan sar', 'Golova', 'Ulas'],
  'Sirnak': ['Merkez', 'Cizre', 'Silopi', 'Idil', 'Uludere', 'Beytussebap', 'Guclukonak'],
  'Tekirdag': ['Suleymanpasa', 'Corlu', 'Cerkezkoy', 'Kapakli', 'Ergene', 'Malkara', 'Muratlı', 'Saray', 'Hayrabolu', 'Sarkoy', 'Marmaraereglisi'],
  'Tokat': ['Merkez', 'Turhal', 'Erbaa', 'Niksar', 'Zile', 'Resadiye', 'Almus', 'Artova', 'Basciftlik', 'Pazar', 'Sulusaray', 'Yesilyurt'],
  'Trabzon': ['Ortahisar', 'Akcaabat', 'Arakli', 'Of', 'Yomra', 'Besikduzu', 'Vakfikebir', 'Caykara', 'Surmene', 'Macka', 'Tonya', 'Dernekpazari', 'Düzköy', 'Hayrat', 'Koprubasi', 'Salpazari'],
  'Tunceli': ['Merkez', 'Pertek', 'Ovacik', 'Hozat', 'Nazimiye', 'Mazgirt', 'Cemisgezek', 'Pulumur'],
  'Usak': ['Merkez', 'Banaz', 'Esme', 'Sivasli', 'Karahalli', 'Ulubey'],
  'Van': ['Ipekyolu', 'Tusba', 'Edremit', 'Ercis', 'Baskale', 'Gevas', 'Gurpinar', 'Muradiye', 'Ozalp', 'Saray', 'Caldiran', 'Bahcesaray'],
  'Yalova': ['Merkez', 'Termal', 'Ciftlikkoy', 'Cinarcik', 'Altinova', 'Armutlu'],
  'Yozgat': ['Merkez', 'Sorgun', 'Bozok', 'Yerköy', 'Akdagmadeni', 'Saraykent', 'Sefaatli', 'Aydincik', 'Bogazliyan', 'Candir', 'Cayiralan', 'Kadisehri', 'Sarikaya', 'Yenifakili'],
  'Zonguldak': ['Merkez', 'Eregli', 'Caycuma', 'Devrek', 'Alapli', 'Gokcebey', 'Kilimli', 'Kozlu'],
}

export const cityNames = Object.keys(cities).sort()
